name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.22-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.22-

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Get tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: changelog
      run: |
        if [ -f CHANGELOG.md ]; then
          # Extract changelog for this version
          awk '/^## \[${{ steps.tag.outputs.tag }}\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md > current_changelog.md || echo "No changelog entry found for ${{ steps.tag.outputs.tag }}" > current_changelog.md
        else
          echo "No CHANGELOG.md found" > current_changelog.md
        fi

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: Release ${{ steps.tag.outputs.tag }}
        body_path: current_changelog.md
        draft: false
        prerelease: ${{ contains(steps.tag.outputs.tag, '-') }}

  go-proxy:
    name: Trigger Go Proxy
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Trigger Go Proxy
      run: |
        curl -X GET "https://proxy.golang.org/github.com/0ffsideCompass/api-football-go-client/@v/${{ github.ref_name }}.info" || true